IF EXISTS (SELECT * FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('dbo.T_SALDOS') AND Name = 'PK_T_SALDOS')
   ALTER TABLE dbo.T_SALDOS
   DROP CONSTRAINT PK_T_SALDOS
GO

IF EXISTS (SELECT * FROM sys.columns WHERE Name = 'Id' AND object_id = OBJECT_ID('dbo.T_SALDOS'))
    ALTER TABLE dbo.T_SALDOS DROP COLUMN RowId
GO

ALTER TABLE dbo.T_SALDOS 
ADD RowId INT IDENTITY(1,1)
GO

ALTER TABLE dbo.T_SALDOS
ADD CONSTRAINT PK_T_SALDOS
PRIMARY KEY CLUSTERED (RowId, CREDITO)
GO

--sp_help t_saldos